import axios from "axios";
import koreaDistricts from "@shared/assets/korea_districts.json";

let localDistrictCoords: Record<
  string,
  { lat: number; lon: number; name?: string }
> = {};
try {
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  // Load precomputed coords mapping if present (generated by scripts/generate-district-coords.cjs)
  // This is optional; if mapping not present, fallback to online geocoding.
  // @ts-ignore
  localDistrictCoords = require("@shared/assets/korea_districts_with_coords.json");
} catch (e) {
  localDistrictCoords = {};
}

export interface Location {
  id: number | string;
  name: string;
  latitude: number;
  longitude: number;
  country: string;
  admin1?: string;
  admin2?: string;
  source?: "local" | "api";
}

// 단순 문자열로 된 행정구역 목록 항목 타입 (예: "서울특별시-종로구-청운동")
export type District = string;

// 빠른 로컬 검색: korea_districts.json에서 단순 매칭 결과만 반환
export const searchDistricts = async (query: string): Promise<District[]> => {
  if (!query || query.length < 2) return [];
  const normalized = query.toLowerCase().trim();
  const results = (koreaDistricts as string[])
    .filter((d) => {
      const lower = d.toLowerCase();
      return lower.includes(normalized) || d.includes(query);
    })
    .slice(0, 10);
  return results;
};

interface GeocodingApiResponse {
  results?: {
    id: number;
    name: string;
    latitude: number;
    longitude: number;
    country: string;
    admin1?: string;
    admin2?: string;
  }[];
}

const GEOCODING_API_URL = "https://geocoding-api.open-meteo.com/v1/search";

// 로컬 한국 지역 검색

// 지역명 → 좌표 변환 캐시
const geocodeCache = new Map<string, Location>();

// 비동기: koreaDistricts에서 지역명으로 좌표를 API로 받아옴
async function searchKoreaDistrictsWithGeocoding(
  query: string
): Promise<Location[]> {
  const normalizedQuery = query.toLowerCase().trim();
  const results: Location[] = [];
  const seen = new Set<string>();

  // 지역명 필터링
  const filtered = koreaDistricts
    .filter((district: string) => {
      const lower = district.toLowerCase();
      return lower.includes(normalizedQuery) || district.includes(query);
    })
    .slice(0, 10); // 너무 많으면 10개만

  for (const district of filtered) {
    if (geocodeCache.has(district)) {
      const cached = geocodeCache.get(district)!;
      if (!seen.has(cached.name)) {
        seen.add(cached.name);
        results.push(cached);
      }
      continue;
    }
    try {
      const apiResults = await searchGeocodingApi(district);
      if (apiResults.length > 0) {
        const loc = apiResults[0];
        geocodeCache.set(district, loc);
        if (!seen.has(loc.name)) {
          seen.add(loc.name);
          results.push(loc);
        }
      }
    } catch (e) {
      // 무시
    }
  }
  return results;
}

// API를 통한 지역 검색
async function searchGeocodingApi(query: string): Promise<Location[]> {
  try {
    console.log("[Geocoding API] Query:", query);
    const response = await axios.get<GeocodingApiResponse>(GEOCODING_API_URL, {
      params: {
        name: query,
        count: 10,
        language: "ko",
        format: "json",
      },
    });

    console.log("[Geocoding API] Response:", response.data);

    if (!response.data.results || response.data.results.length === 0) {
      console.log("[Geocoding API] No results found");
      return [];
    }

    return response.data.results.map((item) => ({
      id: item.id,
      name: item.name,
      latitude: item.latitude,
      longitude: item.longitude,
      country: item.country,
      admin1: item.admin1,
      admin2: item.admin2,
      source: "api",
    }));
  } catch (error) {
    if (axios.isAxiosError(error)) {
      console.error("[Geocoding API] Error:", error.message);
    } else {
      console.error("[Geocoding API] Unexpected error:", error);
    }
    return [];
  }
}

// 단일 지역 문자열에 대해 좌표를 얻어오는 유틸 (캐시 사용)
export const getCoordsForDistrict = async (
  district: string
): Promise<{ lat: number; lon: number } | null> => {
  if (!district) return null;

  // 1) 빠른 로컬 매핑 조회
  if (localDistrictCoords && localDistrictCoords[district]) {
    const v = localDistrictCoords[district];
    return { lat: v.lat, lon: v.lon };
  }

  if (geocodeCache.has(district)) {
    const cached = geocodeCache.get(district)!;
    return { lat: cached.latitude, lon: cached.longitude };
  }

  // 여러 표기(원본, 공백 치환, 역순(동,구,시))으로 API를 시도 (fallback)
  const candidates = new Set<string>();
  candidates.add(district);
  candidates.add(district.replace(/-/g, " "));

  const parts = district
    .split("-")
    .map((p) => p.trim())
    .filter(Boolean);
  if (parts.length > 1) {
    const reversed = parts.slice().reverse().join(", ");
    candidates.add(reversed);
    candidates.add(parts.slice().reverse().join(" "));
  }

  for (const q of Array.from(candidates)) {
    try {
      console.log("[Geocoding API] Try query:", q);
      const apiResults = await searchGeocodingApi(q);
      if (apiResults.length > 0) {
        const loc = apiResults[0];
        geocodeCache.set(district, loc);
        return { lat: loc.latitude, lon: loc.longitude };
      }
    } catch (e) {
      console.error("[getCoordsForDistrict] error for", q, e);
    }
  }

  return null;
};

// 통합 검색 함수
export const searchLocations = async (query: string): Promise<Location[]> => {
  if (!query || query.length < 2) {
    console.log("[Search] Query too short:", query);
    return [];
  }

  console.log("[Search] Starting search for:", query);

  // 한글이 포함되어 있으면 koreaDistricts + API 우선
  const hasKorean = /[\u3131-\u314e|\u314f-\u3163|\uac00-\ud7a3]/.test(query);

  let results: Location[] = [];

  if (hasKorean) {
    // 한글 검색: koreaDistricts + API
    results = await searchKoreaDistrictsWithGeocoding(query);
    if (results.length === 0) {
      const apiResults = await searchGeocodingApi(query);
      results = apiResults;
    }
  } else {
    // 영문 검색: API
    results = await searchGeocodingApi(query);
  }

  // 중복 제거
  const uniqueResults = results.filter(
    (item, index, self) =>
      index ===
      self.findIndex(
        (t) =>
          t.name === item.name &&
          Math.abs(t.latitude - item.latitude) < 0.01 &&
          Math.abs(t.longitude - item.longitude) < 0.01
      )
  );

  return uniqueResults.slice(0, 10);
};
